name: ZaynixFile

options:
  bundleIdPrefix: com.zaynix

targets:

  ZaynixFile:

    type: application

    platform: iOS

    deploymentTarget: "26.0"

    sources:
      - ios/ZaynixFile

    settings:

      base:
        PRODUCT_BUNDLE_IDENTIFIER:
          com.zaynix.file

        SWIFT_VERSION:
          5.0
