name: Zaynix iOS Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install XcodeGen
        run: |
          brew install xcodegen

      - name: XcodeGen Generate
        run: |
          xcodegen generate

      - name: Xcode Build Project
        run: |
          xcodebuild \
            -project ZaynixFile.xcodeproj \
            -scheme ZaynixFile \
            -sdk iphoneos \
            -configuration Release \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGN_IDENTITY="" \
            build
            
